"""empty message

Revision ID: 550881ceb20c
Revises: 390319d12874
Create Date: 2024-10-28 23:51:18.714899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '550881ceb20c'
down_revision = '390319d12874'
branch_labels = None
depends_on = None


def upgrade():
    # No eliminar las tablas
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
        sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='user_pkey'),
        sa.UniqueConstraint('email', name='user_email_key'),
        sa.UniqueConstraint('username', name='user_username_key'),
        postgresql_ignore_search_path=False
    )
    op.create_table('planets',
        sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planets_id_seq'::regclass)"), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('climate', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('diameter', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('gravity', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('orbital_period', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('residents', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('rotation_period', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('surface_water', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('terrain', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='planets_pkey'),
        sa.UniqueConstraint('name', name='planets_name_key'),
        sa.UniqueConstraint('url', name='planets_url_key'),
        postgresql_ignore_search_path=False
    )
    op.create_table('favorites',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='favorites_person_id_fkey'),
        sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='favorites_planet_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favoritos_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='favoritos_pkey'),
        sa.UniqueConstraint('user_id', 'person_id', name='unique_favorite_person'),
        sa.UniqueConstraint('user_id', 'planet_id', name='unique_favorite_planet')
    )
    op.create_table('people',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('birth_year', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('eye_color', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('films', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('hair_color', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('homeworld', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('mass', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('skin_color', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('edited', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('species', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('starships', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('vehicles', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='people_pkey'),
        sa.UniqueConstraint('name', name='people_name_key'),
        sa.UniqueConstraint('url', name='people_url_key')
    )
    # ### end Alembic commands ###

